name: alarm

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches:
      - main
      - staging
      - develop

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    runs-on: ubuntu-latest
    name: Send to slack channel
    steps:
      - name: Check env variable
        run: echo $SECRET_VAR
      - name: send message
        run: echo "send message"
