name: alarm

on:
  workflow_run:
    workflows: ["main"]
    types: [completed]
    branches:
      - main
      - staging
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
