name: alarm

on:
  workflow_run:
    workflows: ["build"]
    types: [completed]
    branches:
      - main
      - staging
      - develop

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
