name: build

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"

env:
  SECRET_VAR: 123

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: print secret var
        run: echo $SECRET_VAR
      - name: build
        uses: jakejarvis/wait-action@master
        with:
          time: "10s"
