name: build

on:
  pull_request:
  push:
    branches:
      - "main"
      - "test"
jobs:
  prepare:
    runs-on: ubuntu-18.04
    steps:
      - run: touch prepare.txt
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: touch build.txt
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: touch test.txt
  deploy:
    runs-on: ubuntu-18.04
    needs: [build, test]
    steps:
      - run: ls -al
