name: build

on:
  pull_request:
  push:
    branches:
      - "main"
      - "test"
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        uses: jakejarvis/wait-action@master
        with:
          time: "10s"
