name: test

on:
  pull_request:
  push:
    branches:
      - "main"
      - "test"

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: build
        uses: jakejarvis/wait-action@master
        with:
          time: "30s"
      - run: exit 1
